name: build

on: [push, pull_request]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        cc: ["gcc", "clang"]
    env:
      CC: "${{ matrix.cc }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libxkbcommon-dev xorg-dev
      - name: Build
        run: ./build.sh

  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { sys: ucrt64,  env: ucrt-x86_64,  cc: "gcc" }
          - { sys: clang64, env: clang-x86_64, cc: "clang" }
    env:
      CC: "${{ matrix.cc }}"
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v4
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: git mingw-w64-${{matrix.env}}-${{matrix.cc}}

      - name: Build
        run: NO_MATLAB=1 ./build.sh
